export const SKILLS = [
    { value: 'Java' },
    { value: 'Angular' },
    { value: 'CSS' },
    { value: 'HTML' },
    { value: 'JavaScript' },
    { value: 'UI' },
    { value: 'SQL' },
    { value: 'React' },
    { value: 'PHP' },
    { value: 'Git' },
    { value: 'AWS' },
    { value: 'Python' },
    { value: 'Django' },
    { value: 'C' },
    { value: 'C++' },
    { value: 'Unity' },
    { value: 'R' },
    { value: 'AI' },
    { value: 'NLP' },
    { value: 'Photoshop' },
    { value: 'NodeJs' },
]